# 18 - Numpy Array

In [3]:
import numpy as np

arr = np.array([1,2,3,4,5])

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
arr = np.arange(1,10)

In [6]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr = np.arange(1,11, 2)

In [8]:
arr

array([1, 3, 5, 7, 9])

In [9]:
arr = np.arange(0, 11, 2)

In [10]:
arr

array([ 0,  2,  4,  6,  8, 10])

In [11]:
arr = np.zeros(3)

In [12]:
arr

array([0., 0., 0.])

In [13]:
arr = np.zeros((3,3))

In [14]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
arr = np.ones(4)

In [16]:
arr

array([1., 1., 1., 1.])

In [17]:
arr = np.ones((3,3))

In [18]:
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
arr = np.linspace(0,5,10)

In [21]:
arr

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [22]:
arr = np.eye(4)

In [23]:
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
arr = np.random.rand(5)

In [25]:
arr

array([0.87171555, 0.75318501, 0.48803704, 0.11609185, 0.63204386])

In [26]:
arr = np.random.rand(5,5)

In [27]:
arr

array([[0.2673511 , 0.26960075, 0.49150442, 0.74489351, 0.94082312],
       [0.34072263, 0.34727528, 0.44360393, 0.69509093, 0.1220956 ],
       [0.70888242, 0.66188005, 0.35695638, 0.67833145, 0.31967148],
       [0.6943193 , 0.05275025, 0.80625217, 0.03500989, 0.2898455 ],
       [0.02259936, 0.12788865, 0.84324841, 0.83976571, 0.15109361]])

In [28]:
arr = np.random.rand(5,5,5)

In [29]:
arr

array([[[0.71171738, 0.00899134, 0.28661984, 0.88568166, 0.88303885],
        [0.94180739, 0.23146359, 0.59254448, 0.31031251, 0.50247443],
        [0.89878042, 0.01509873, 0.53565952, 0.845495  , 0.37752463],
        [0.32369445, 0.98188249, 0.15006754, 0.32913189, 0.73322904],
        [0.61986549, 0.94562479, 0.58863531, 0.21677516, 0.32218317]],

       [[0.84256568, 0.67692991, 0.73661082, 0.57715146, 0.70290548],
        [0.48734588, 0.99679227, 0.64341861, 0.97386439, 0.73412076],
        [0.97418334, 0.97746144, 0.5281504 , 0.19361715, 0.24997314],
        [0.10241061, 0.95752485, 0.62532094, 0.42457192, 0.64547598],
        [0.32207612, 0.93050711, 0.60037681, 0.41029376, 0.77407773]],

       [[0.93465516, 0.38767981, 0.52233713, 0.78473418, 0.51673054],
        [0.03664368, 0.1709105 , 0.55642041, 0.51482712, 0.4725595 ],
        [0.59814853, 0.7887032 , 0.02066263, 0.98630025, 0.98240947],
        [0.44579257, 0.91932709, 0.41522536, 0.48794605, 0.46818654],
        [0.11967

In [30]:
arr = np.random.rand(3,3,3)

In [31]:
arr

array([[[0.89216514, 0.28693539, 0.97190953],
        [0.21043442, 0.86769765, 0.4997951 ],
        [0.08554023, 0.08876811, 0.73193398]],

       [[0.12533482, 0.05739923, 0.49993669],
        [0.48241053, 0.97251239, 0.55249478],
        [0.7859987 , 0.21886572, 0.36001726]],

       [[0.44421081, 0.89837862, 0.39136891],
        [0.19565904, 0.05299205, 0.49094037],
        [0.26033864, 0.93086366, 0.87307068]]])

In [41]:
arr = np.random.rand(3)

In [42]:
arr

array([0.37566256, 0.0279122 , 0.84876124])

In [43]:
arr = np.random.randn(3)

In [44]:
arr

array([ 0.20115799, -0.78836225,  0.95600698])

In [47]:
arr = np.random.randint(1,100, 10)

In [48]:
arr

array([43, 71, 73, 42, 16, 70, 89, 72, 88, 39])

In [49]:
arr = np.arange(25)

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [56]:
ranarr = np.random.randint(0, 50, 10)

In [57]:
ranarr

array([10, 24,  4, 49, 49, 26, 23, 45, 39, 31])

In [58]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [59]:
ranarr.max()

49

In [60]:
ranarr.min()

4

In [61]:
ranarr.argmax()

3

In [62]:
ranarr.argmin()

2

In [63]:
arr.shape

(25,)

In [66]:
arr.dtype

dtype('int32')

# 20 Numpy Array Indexing

In [1]:
import numpy as np

In [5]:
arr = np.arange(0, 11)

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[8]

8

In [8]:
arr[1:8]

array([1, 2, 3, 4, 5, 6, 7])

In [9]:
arr[0:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [11]:
arr[:4]

array([0, 1, 2, 3])

In [12]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [13]:
arr[0:5] = 100

In [14]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [15]:
slice_of_arr = arr[0:5]

In [16]:
slice_of_arr

array([100, 100, 100, 100, 100])

In [17]:
slice_of_arr[:] = 99

In [18]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [19]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [26]:
# Creates a deep copy by calling the copy method on the array
slice_of_arr1 = arr.copy()

In [27]:
slice_of_arr1

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [28]:
slice_of_arr1[0:5] = 28

In [29]:
slice_of_arr1

array([28, 28, 28, 28, 28,  5,  6,  7,  8,  9, 10])

In [30]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [31]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])

In [32]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [34]:
arr_2d[0][2]

15

In [35]:
arr_2d[1]

array([20, 25, 30])

In [36]:
arr_2d[0,2]

15

In [37]:
arr_2d[1,1]

25