# 18. Numpy Array

In [3]:
import numpy as np

arr = np.array([1,2,3,4,5])

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
arr = np.arange(1,10)

In [6]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr = np.arange(1,11, 2)

In [8]:
arr

array([1, 3, 5, 7, 9])

In [9]:
arr = np.arange(0, 11, 2)

In [10]:
arr

array([ 0,  2,  4,  6,  8, 10])

In [11]:
arr = np.zeros(3)

In [12]:
arr

array([0., 0., 0.])

In [13]:
arr = np.zeros((3,3))

In [14]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
arr = np.ones(4)

In [16]:
arr

array([1., 1., 1., 1.])

In [17]:
arr = np.ones((3,3))

In [18]:
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
arr = np.linspace(0,5,10)

In [21]:
arr

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [22]:
arr = np.eye(4)

In [23]:
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
arr = np.random.rand(5)

In [25]:
arr

array([0.87171555, 0.75318501, 0.48803704, 0.11609185, 0.63204386])

In [26]:
arr = np.random.rand(5,5)

In [27]:
arr

array([[0.2673511 , 0.26960075, 0.49150442, 0.74489351, 0.94082312],
       [0.34072263, 0.34727528, 0.44360393, 0.69509093, 0.1220956 ],
       [0.70888242, 0.66188005, 0.35695638, 0.67833145, 0.31967148],
       [0.6943193 , 0.05275025, 0.80625217, 0.03500989, 0.2898455 ],
       [0.02259936, 0.12788865, 0.84324841, 0.83976571, 0.15109361]])

In [28]:
arr = np.random.rand(5,5,5)

In [29]:
arr

array([[[0.71171738, 0.00899134, 0.28661984, 0.88568166, 0.88303885],
        [0.94180739, 0.23146359, 0.59254448, 0.31031251, 0.50247443],
        [0.89878042, 0.01509873, 0.53565952, 0.845495  , 0.37752463],
        [0.32369445, 0.98188249, 0.15006754, 0.32913189, 0.73322904],
        [0.61986549, 0.94562479, 0.58863531, 0.21677516, 0.32218317]],

       [[0.84256568, 0.67692991, 0.73661082, 0.57715146, 0.70290548],
        [0.48734588, 0.99679227, 0.64341861, 0.97386439, 0.73412076],
        [0.97418334, 0.97746144, 0.5281504 , 0.19361715, 0.24997314],
        [0.10241061, 0.95752485, 0.62532094, 0.42457192, 0.64547598],
        [0.32207612, 0.93050711, 0.60037681, 0.41029376, 0.77407773]],

       [[0.93465516, 0.38767981, 0.52233713, 0.78473418, 0.51673054],
        [0.03664368, 0.1709105 , 0.55642041, 0.51482712, 0.4725595 ],
        [0.59814853, 0.7887032 , 0.02066263, 0.98630025, 0.98240947],
        [0.44579257, 0.91932709, 0.41522536, 0.48794605, 0.46818654],
        [0.11967

In [30]:
arr = np.random.rand(3,3,3)

In [31]:
arr

array([[[0.89216514, 0.28693539, 0.97190953],
        [0.21043442, 0.86769765, 0.4997951 ],
        [0.08554023, 0.08876811, 0.73193398]],

       [[0.12533482, 0.05739923, 0.49993669],
        [0.48241053, 0.97251239, 0.55249478],
        [0.7859987 , 0.21886572, 0.36001726]],

       [[0.44421081, 0.89837862, 0.39136891],
        [0.19565904, 0.05299205, 0.49094037],
        [0.26033864, 0.93086366, 0.87307068]]])

In [41]:
arr = np.random.rand(3)

In [42]:
arr

array([0.37566256, 0.0279122 , 0.84876124])

In [43]:
arr = np.random.randn(3)

In [44]:
arr

array([ 0.20115799, -0.78836225,  0.95600698])

In [47]:
arr = np.random.randint(1,100, 10)

In [48]:
arr

array([43, 71, 73, 42, 16, 70, 89, 72, 88, 39])

In [49]:
arr = np.arange(25)

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [56]:
ranarr = np.random.randint(0, 50, 10)

In [57]:
ranarr

array([10, 24,  4, 49, 49, 26, 23, 45, 39, 31])

In [58]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [59]:
ranarr.max()

49

In [60]:
ranarr.min()

4

In [61]:
ranarr.argmax()

3

In [62]:
ranarr.argmin()

2

In [63]:
arr.shape

(25,)

In [66]:
arr.dtype

dtype('int32')

# 20. Numpy Array Indexing

In [1]:
import numpy as np

In [5]:
arr = np.arange(0, 11)

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[8]

8

In [8]:
arr[1:8]

array([1, 2, 3, 4, 5, 6, 7])

In [9]:
arr[0:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [11]:
arr[:4]

array([0, 1, 2, 3])

In [12]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [13]:
arr[0:5] = 100

In [14]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [15]:
slice_of_arr = arr[0:5]

In [16]:
slice_of_arr

array([100, 100, 100, 100, 100])

In [17]:
slice_of_arr[:] = 99

In [18]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [19]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [26]:
# Creates a deep copy by calling the copy method on the array
slice_of_arr1 = arr.copy()

In [27]:
slice_of_arr1

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [28]:
slice_of_arr1[0:5] = 28

In [29]:
slice_of_arr1

array([28, 28, 28, 28, 28,  5,  6,  7,  8,  9, 10])

In [30]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [31]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])

In [32]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [34]:
arr_2d[0][2]

15

In [35]:
arr_2d[1]

array([20, 25, 30])

In [36]:
arr_2d[0,2]

15

In [37]:
arr_2d[1,1]

25

In [42]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [45]:
arr = np.arange(1, 11)

In [46]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
bool_arr = arr > 5

In [49]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [50]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [51]:
arr[arr < 5]

array([1, 2, 3, 4])

In [52]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
arr_2d = np.arange(50).reshape(5,10)

In [54]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [59]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [60]:
arr_2d[1:3,3:7]

array([[13, 14, 15, 16],
       [23, 24, 25, 26]])

# 21. Numpy Operations

In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11
                )

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [6]:
arr * 10

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [7]:
arr /arr

C:\Users\suraj\AppData\Local\Temp\ipykernel_8504\591710190.py:1: RuntimeWarning: invalid value encountered in divide
  arr /arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [8]:
1 / arr

C:\Users\suraj\AppData\Local\Temp\ipykernel_8504\1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [9]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [10]:
new_arr = arr ** 2

In [11]:
np.sqrt(new_arr)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [12]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [13]:
np.max(arr)

10

In [14]:
arr.max()

10

In [15]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [16]:
np.log(arr)

C:\Users\suraj\AppData\Local\Temp\ipykernel_8504\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

# 23. Numpy Exercises

In [17]:
import numpy as np

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [21]:
np.zeros(10) + 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [22]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [23]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [25]:
arr = np.arange(9)

In [26]:
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
np.random.rand(1)

array([0.96978662])

In [33]:
arr = np.random.randn(25)

In [35]:
arr

array([-0.19252767, -0.43075502, -0.82985868,  0.16791501,  0.90164832,
        0.28002866, -0.06957124, -0.77647189,  0.22155568, -1.52547414,
       -0.64532591, -1.83086495, -1.43393664,  1.3043298 ,  0.02942472,
       -0.8046048 , -1.18747549, -1.19395576, -0.07995705,  1.31598402,
        0.19639072, -0.29198472,  0.40357884, -0.46934043, -0.57848021])

In [36]:
arr.shape

(25,)

In [39]:
np.arange(1,101).reshape(10, 10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [42]:
np.linspace(0.01,1, 100).reshape(10, 10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [43]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

# Numpy indexing exercise

In [44]:
mat = np.arange(1, 26).reshape(5,5)

In [45]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [47]:
mat[2:, 1:4]

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [48]:
mat[3,4]

20

In [54]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [55]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [58]:
mat[-1:,:]

array([[21, 22, 23, 24, 25]])

In [60]:
mat[3:, :4]

array([[16, 17, 18, 19],
       [21, 22, 23, 24]])

In [61]:
mat.sum()

325

In [64]:
np.std(mat)

7.211102550927978

In [65]:
mat.std()

7.211102550927978

In [67]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])